- name: Ensure all (apt) packages are up to date
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: "yes"
  register: updates

- name: Install Docker
  include_role:
    name: install_docker

- name: Ask GitHub for an Action registration token
  uri:
    url: "https://api.github.com/repos/{{ github_org }}/{{ github_repo }}/actions/runners/registration-token"
    method: POST
    headers:
      Accept: application/vnd.github+json
      Authorization: "Bearer {{ github_token }}"
    status_code: [201]
  register: registration_token_response

- name: Store registration token
  set_fact:
    runner_token: "{{ registration_token_response | json_query('json.token') }}"

- name: Display registration token
  debug:
    msg: "{{ runner_token }}"

- name: Ensure system is rebooted
  become: true
  reboot:
    msg: Rebooting post package update
  when: updates.changed
