---
- name: Ensure instance is running
  openstack.cloud.server:
    state: present
    cloud: "{{ cloud_id }}"
    name: "{{ instance_name }}"
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    auto_ip: false
    security_groups:
      - default
    wait: true
  register: instances_output

- name: Store instance IP address
  ansible.builtin.set_fact:
    runner_ip: "{{ instances_output | json_query('server.addresses.Internal[0].addr') }}"

- name: Display runner ip
  ansible.builtin.debug:
    msg: "{{ runner_ip }}"

- name: Add runner to a host group
  ansible.builtin.add_host:
    name: "{{ runner_ip }}"
    groups: gha_runner
